name: Build check

on:
    push:
        branches:
            - master

jobs: 
    build:

        runs-on: ubuntu-22.04

        permissions:
            contents: read

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4